apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  namespace: argocd
  labels:
    env: dev
spec:
  project: default
  source:
    repoURL: cnoe://argo-events/manifests
    targetRevision: HEAD
    path: "."
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argo-events
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
